config/routes.rb
ProjectManager::Application.routes.draw do
  
  resources :people
  

end

app/models/person.rb
class Person < ActiveRecord::Base
  
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  
  before_save :cleanup
  
  scope :all_lazy, select('*')
  scope :find_lazy, lambda {|id| where (:id => id) }
  
  def name
    "#{first_name} #{last_name}"
  end
  
  private
  
  def cleanup
    self[:first_name] = self[:first_name].capitalize
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  before_filter :authenticate, :only => :show
  
  def index
    @people = [
        'luke-skywalker',
        'darth-vader' 
      ]
  end
  
  def show
    @person = params[:id]
  end
  
  private 
  
  def authenticate
    if params[:id] == "darth-vader"
      redirect_to people_url, :notice => "Accesso negato."
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManager</title>
	<%= render :partial => "shared/includes" %>
</head>
<body>

<p> <%= notice %> </p>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>Project Manager - People</h1>
<p>Welcome</p>

<ul>
<% @people.each do |person| %>
		<li><%= link_to person, person_path(person) %></li>
<% end %>
</ul>

app/views/people/show.html.erb
<h1> Show </h1>
<%= @person %>

<p> <%= link_to "Menu persone", people_path%>

app/views/shared/_includes.html.erb
<%= stylesheet_link_tag 'scaffold', 'application'  %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>